# Generated by Django 4.1.7 on 2023-04-13 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cities1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.CharField(help_text='The name of city, which you are leaving', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cities2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city2', models.CharField(help_text='The name of city, where you are arriving', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Countries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(help_text='Country name', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(help_text='Company name', max_length=70)),
                ('time1', models.DateTimeField(help_text='Time of leaving city1')),
                ('time2', models.DateTimeField(help_text='Time of arriving at city2')),
                ('price', models.IntegerField(help_text='The price of your ticket')),
                ('city1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.cities1')),
                ('city2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.cities2')),
            ],
        ),
        migrations.AddField(
            model_name='cities2',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.countries'),
        ),
        migrations.AddField(
            model_name='cities1',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='mainpage.countries'),
        ),
    ]
