# Generated by Django 4.1.7 on 2023-04-20 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Direction1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city1', models.CharField(help_text='The name of city, which you are leaving', max_length=50)),
                ('country1', models.CharField(help_text='The name of country, which you are leaving', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Direction2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city2', models.CharField(help_text='The name of city, where you are arriving', max_length=50)),
                ('country2', models.CharField(help_text='The name of country, where you are arriving', max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='cities1',
            name='country',
        ),
        migrations.RemoveField(
            model_name='cities2',
            name='country',
        ),
        migrations.DeleteModel(
            name='Countries',
        ),
        migrations.AlterField(
            model_name='ticket',
            name='city1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.direction1'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='city2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.direction2'),
        ),
        migrations.DeleteModel(
            name='Cities1',
        ),
        migrations.DeleteModel(
            name='Cities2',
        ),
    ]
