# Generated by Django 4.1.7 on 2023-05-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0004_examplemodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'Ticket', 'verbose_name_plural': 'Tickets'},
        ),
        migrations.AlterField(
            model_name='ticket',
            name='city1',
            field=models.CharField(help_text='The name of city, which you are leaving', max_length=50),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='city2',
            field=models.CharField(help_text='The name of city, where you are arriving', max_length=50),
        ),
        migrations.DeleteModel(
            name='Direction1',
        ),
        migrations.DeleteModel(
            name='Direction2',
        ),
    ]
